apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controle-estoque.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "controle-estoque.name" . }}
    helm.sh/chart: {{ include "controle-estoque.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  POSTGRES_HOST: {{ .Values.postgres.host | quote }}
  POSTGRES_PORT: {{ .Values.postgres.port | toString | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  JDBC_URL: {{ if .Values.postgres.jdbcUrl }}{{ .Values.postgres.jdbcUrl | quote }}{{ else }}{{ printf "jdbc:postgresql://%s:%d/%s?createDatabaseIfNotExist=true" .Values.postgres.host .Values.postgres.port .Values.postgres.database | quote }}{{ end }}
