image:
  repository: ghcr.io/RafaelGabriel325/api-controle-de-estoque
  tag: "dev-0.1.0"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  SPRING_PROFILES_ACTIVE: dev

postgres:
  host: ce-pg-rw.dev.svc.cluster.local
  port: 5432
  database: controleestoque
  username: postgres
  password: devpassword
  jdbcUrl: ""

ingress:
  enabled: false
